#!/usr/bin/env bash

# This script will replace your local DB contents with the contents
# of Production's follower DB. All data is deleted from your local
# database before restoring from Production.

set -euo pipefail

dropdb -h localhost door_keeper_development || true
heroku pg:pull DATABASE_URL door_keeper_development --app door-keeper-production
